AppJugueteria/Controllers/JuguetesController.cs
using ApiJuguetes.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AppJugueteria.Controllers
{
    public class JuguetesController : Controller
    {
        public HttpClient _client = new HttpClient();
        public string url = ConfigurationManager.AppSettings["ApiUrl"];

        public class Respuesta
        {
            public bool Error { get; set; }
            public string Data { get; set; }
        }

        // GET: Juguetes
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View();
        }

        //Obtener lista de juguetes
        public async Task<ActionResult> Get()
        {

            Uri uri = new Uri(string.Format(url, string.Empty));
            ActionResult res = null;

            try
            {
                HttpResponseMessage response = await _client.GetAsync(uri);
                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    res = Json(new Respuesta { Error = false, Data = content }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                res = Json(new Respuesta { Error = true, Data = ex.Message });
            }

            return res;
        }


        //Agregar o actualizar un juguete 
        public async Task<ActionResult> Post(int Id, string Nombre, string Descripcion, int RestriccionEdad, string Compania, decimal Precio)
        {
            Uri uri = new Uri(string.Format(url, string.Empty));
            ActionResult res = null;

            Juguetes obj = new Juguetes
            {
                Id = Id,
                Nombre = Nombre,
                Descripcion = Descripcion,
                RestriccionEdad = RestriccionEdad,
                Compania = Compania,
                Precio = Precio
            };

            try
            {
                string json = JsonConvert.SerializeObject(obj);
                StringContent content = new StringContent(json, Encoding.UTF8, "application/json");

                HttpResponseMessage response = null;
                if (Id == 0)
                    response = await _client.PostAsync(uri, content);
                else
                    response = await _client.PutAsync(uri + Id.ToString(), content);

                if (response.IsSuccessStatusCode)
                {
                    res = Json(new Respuesta{ Error = false, Data = json });
                }

            }
            catch (Exception ex)
            {
                res = Json(new Respuesta{ Error = true, Data = ex.Message});
            }
            return res;
        }

        //Eliminar un juguete
        public async Task<ActionResult> Delete(int Id)
        {
            url +=  Id;
            Uri uri = new Uri(url);
            ActionResult res = null;

            try
            {
                HttpResponseMessage response = await _client.DeleteAsync(uri);
                if (response.IsSuccessStatusCode)
                    res = Json(new Respuesta { Error = false, Data = Id.ToString() });
            }
            catch (Exception ex)
            {
                res = Json(new Respuesta { Error = true, Data = ex.Message });
            }
            return res;
        }


    }

}

AppJugueteria/Views/Juguetes/Contact.cshtml
@{
    ViewBag.Title = "Contacto";
}
<h2>@ViewBag.Title.</h2>

<h2><strong>Abraham Oswaldo Andrade García</strong></h2>
<h3>Desarrollador de software</h3>
<br />
<div>
    <address>
        <strong>Teléfono:</strong>667-354-1999<br />
    </address>
</div>

<div>
    <address>
        <strong>E-mail:</strong> oswaldo.andgar@gmail.com<br />
    </address>
</div>

AppJugueteria/Views/Juguetes/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h2>ADMINISTRACION DE JUGUETERIA</h2>
            </div>
            <div class="card-body">
                <a class="btn btn-success" style="margin-bottom:10px" id="btnNuevo"><i class="fa fa-plus"></i>Agregar Nuevo</a>
                <table id="dtJuguetes" class="table">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nombre</th>
                            <th>Descripción</th>
                            <th>Edad</th>
                            <th>Compañía</th>
                            <th>Precio</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--MODAL PARA AGREGAR O ACTUALIZAR JUGUETE-->
<div class="modal fade" tabindex="-1" role="dialog" id="dvAgregar">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">AGREGAR JUGUETE</h4>
            </div>

            <div class="modal-body">
                <input type="hidden" id="txtId" value="0" />
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label>Nombre</label>
                            <input id="txtNombre" class="form-control" type="text" aria-label="Nombre del juguete" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label>Precio</label>
                            <input id="txtPrecio" class="form-control" type="text" aria-label="Nombre del juguete" onkeypress="return filterFloat(event,this);" maxlength="6" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label>Compania</label>
                            <input id="txtCompania" class="form-control" type="text" aria-label="Nombre del juguete" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label>Edad</label>
                            <input id="txtEdad" class="form-control" type="text" aria-label="Sugerencia de edad" onkeypress="return soloNumeros(event);" maxlength="2" />
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label>Descripcion</label>
                            <textarea class="form-control" rows="3" id="txtDescripcion"></textarea>

                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Regresar</button>
                    <button id="btnAgregar" type="button" class="btn btn-primary">Agregar</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript" src="~/Scripts/Juguetes.js"></script>
    <script type="text/javascript" src="~/Scripts/sweetalert2.all.min.js"></script>
}


AppJugueteria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="~/Content/datatable/css/datatables.min.css">

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ADM JUGUETERIA", "Index", "Juguetes", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Contacto", "Contact", "Juguetes")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Administracion de juguetería</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" charset="utf8" src="~/Content/datatable/js/datatables.min.js"></script>
    <script src="~/Scripts/notify.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>